# This is the configuration file for the data ingestion pipeline script for the province of Québec
# modelEAU lab

colors:
    "0":
      french: "Pas de données"
      english: "No Data"
      color: "#ececec"
    "1": 
      french: "Très faible"
      english: "Very Low"
      color: "#6da06f"
    "2": 
      french: "Faible"
      english: "Low"
      color: "#b6e9d1"
    "3": 
      french: "Moyennement élevé"
      english: "Somewhat high"
      color: "#ffbb43"
    "4": 
      french: "Élevé"
      english: "High"
      color: "#ff8652"
    "5": 
      french: "Très élevé"
      english: "Very high"
      color: "#c13525"

lod: 0.5

logo_path:  "/Users/jeandavidt/dev/modelEAU/ODM Import/Data/images/graph_logos.png"

default_start_date: "2021-01-01"
lvl_start_date: "2020-10-01"

data_folder: "/Users/jeandavidt/OneDrive - Université Laval/COVID/Latest Data/Input" 
csv_folder: "/Users/jeandavidt/OneDrive - Université Laval/COVID/Latest Data/odm_csv"
static_data: "CentrEAU-COVID_Static_Data.xlsx"

inspq_data: ""
inspq_vaccine_data: ""

qc_lab_data: "COVIDProject_Lab Measurements.xlsx"
qc_sheet_name: "Lab analyses"
qc_lab: "modeleau_lab"
qc_geo_path1: "qc1-poly.txt"
qc_geo_path2: "qc2-poly.txt"

qc_city_sensor_folder: "Qc_sensors"
qc_city_plant_folder: "Qc_plant"
qc_city_rain_folder: "Qc_rain"

qc_virus_data: "CentrEau-COVID_Resultats_Quebec_final.xlsx"
qc_virus_sheet_name: "QC Data Daily Samples (McGill)"
qc_quality_sheet_name: "QC_Compil_STEP (int)"
qc_virus_lab: "frigon_lab"

ul_virus_data: "CentrEau-COVID_Resultats_McGill&Laval_Student_Residences.xlsx"
ul_virus_sheet_name: "Data Daily Samples (McGill)"
ul_virus_lab: "frigon_lab"

mtl_lab_data: "CentrEau-COVID_Resultats_Montreal_final.xlsx"
mtl_poly_sheet_name: "Mtl Data Daily Samples (Poly)"
mtl_mcgill_sheet_name: "Mtl Data Daily Samples (McGill)"
mtl_quality_sheet_name: "MTL_Compil_STEP (int)"
mcgill_virus_lab: "frigon_lab"
poly_virus_lab: "dorner_lab"

bsl_lab_data: "CentrEau-COVID_Resultats_BSL_final.xlsx"
bsl_sheet_name: "BSL Data Daily Samples (UQAR)"
bsl_virus_lab: "bsl_lab"
bsl_cities:
  - "stak"
  - "trpis"
  - "mtne"
  - "riki" 
  - "rdl"
bsl_quality_sheet_name: "BSL_Compil_STEP (int)"

lvl_lab_data: "CentrEau-COVID_Resultats_Laval_final.xlsx"
lvl_sheet_name: "LVL_Data Daily Samples (Poly)"
lvl_virus_lab: "dorner_lab"
lvl_quality_sheet_name: "LVL_Compil_ALL (int)"

polygon_output_dir: "/Users/jeandavidt/OneDrive - Université Laval/COVID/Website geo"
poly_name: "polygons.geojson"
polys_to_extract:
  - "swrCat"

site_output_dir: "/Users/jeandavidt/OneDrive - Université Laval/COVID/Website geo"
site_name: "sites.geojson"

plot_langs:
  - "french"

plot_output_dir: "/Users/jeandavidt/OneDrive - Université Laval/COVID/Website figures"
city_output_dir: "/Users/jeandavidt/OneDrive - Université Laval/COVID/Latest Data/wide tables"
