# This is the configuration file for the data ingestion pipeline script for the province of Québec
# modelEAU lab

colors:
  "0":
    french: "Pas de données"
    english: "No Data"
    color: "#ececec"
  "1":
    french: "Très faible"
    english: "Very Low"
    color: "#6da06f"
  "2":
    french: "Faible"
    english: "Low"
    color: "#b6e9d1"
  "3":
    french: "Moyennement élevé"
    english: "Somewhat high"
    color: "#ffbb43"
  "4":
    french: "Élevé"
    english: "High"
    color: "#ff8652"
  "5":
    french: "Très élevé"
    english: "Very high"
    color: "#c13525"

lod: 0.5

default_start_date: "2021-01-01"
lvl_start_date: "2020-10-01"

logo_path: "/Users/jeandavidt/Library/CloudStorage/OneDrive-UniversitéLaval/Université/Doctorat/COVID/Latest Data/Input/Logos/centreau-covid_logos.png"
data_folder: "/Users/jeandavidt/Library/CloudStorage/OneDrive-UniversitéLaval/Université/Doctorat/COVID/Latest Data/Input"
csv_folder: "/Users/jeandavidt/Library/CloudStorage/OneDrive-UniversitéLaval/Université/Doctorat/COVID/Latest Data/odm_csv"
polygon_output_dir: "/Users/jeandavidt/Library/CloudStorage/OneDrive-UniversitéLaval/Université/Doctorat/COVID/Website geo"
site_output_dir: "/Users/jeandavidt/Library/CloudStorage/OneDrive-UniversitéLaval/Université/Doctorat/COVID/Website geo"
plot_output_dir: "/Users/jeandavidt/Library/CloudStorage/OneDrive-UniversitéLaval/Université/Doctorat/COVID/Website figures"
city_output_dir: "/Users/jeandavidt/Library/CloudStorage/OneDrive-UniversitéLaval/Université/Doctorat/COVID/Latest Data/wide tables"

static_data: "Ongoing/CentrEAU-COVID_Static_Data.xlsx"

inspq_data: ""
inspq_vaccine_data: ""

qc_lab_data: "Ongoing/COVIDProject_Lab Measurements.xlsx"
qc_sheet_name: "Lab analyses"
qc_lab: "modeleau_lab"
qc_geo_path1: "qc1-poly.txt"
qc_geo_path2: "qc2-poly.txt"

qc_city_sensor_folder: "2021/Qc_sensors"
qc_city_plant_folder: "2021/Qc_plant"
qc_city_rain_folder: "2021/Qc_rain"

qc_virus_data: "2021/CentrEau-COVID_Resultats_Quebec.xlsx"
qc_virus_sheet_name: "QC Data Daily Samples (McGill)"
qc_quality_sheet_name: "QC_Compil_STEP (int)"
qc_virus_lab: "frigon_lab"

ul_virus_data: "2021/CentrEau-COVID_Resultats_McGill&Laval_Student_Residences.xlsx"
ul_virus_sheet_name: "Data Daily Samples (McGill)"
ul_virus_lab: "frigon_lab"

mtl_lab_data: "2021/CentrEau-COVID_Resultats_Montreal_final.xlsx"
mtl_poly_sheet_name: "Mtl Data Daily Samples (Poly)"
mtl_mcgill_sheet_name: "Mtl Data Daily Samples (McGill)"
mtl_quality_sheet_name: "MTL_Compil_STEP (int)"
mcgill_virus_lab: "frigon_lab"
poly_virus_lab: "dorner_lab"

bsl_lab_data: "2021/CentrEau-COVID_Resultats_BSL_final.xlsx"
bsl_sheet_name: "BSL Data Daily Samples (UQAR)"
bsl_virus_lab: "bsl_lab"
bsl_cities:
  - "stak"
  - "trpis"
  - "mtne"
  - "riki"
  - "rdl"
bsl_quality_sheet_name: "BSL_Compil_STEP (int)"

lvl_lab_data: "2021/CentrEau-COVID_Resultats_Laval_final.xlsx"
lvl_sheet_name: "LVL_Data Daily Samples (Poly)"
lvl_virus_lab: "dorner_lab"
lvl_quality_sheet_name: "LVL_Compil_ALL (int)"

poly_name: "polygons.geojson"
polys_to_extract:
  - "swrCat"

site_name: "sites.geojson"

plot_langs:
  - "french"
  - "english"

health_polygons:
  qc_01: prov_qc_hlthreg_capitale_nationale
  qc_02: prov_qc_hlthreg_capitale_nationale
  qc_03.1: prov_qc_hlthreg_capitale_nationale
  qc_03.2: prov_qc_hlthreg_capitale_nationale
  qc_03.3: prov_qc_hlthreg_capitale_nationale
  qc_04: prov_qc_hlthreg_capitale_nationale
  qc_05: prov_qc_hlthreg_capitale_nationale
  qc_06.1: prov_qc_hlthreg_capitale_nationale
  qc_06.2: prov_qc_hlthreg_capitale_nationale
  qc_07.1: prov_qc_hlthreg_capitale_nationale
  qc_07.2: prov_qc_hlthreg_capitale_nationale
  qc_08: prov_qc_hlthreg_capitale_nationale
  qc_09: prov_qc_hlthreg_capitale_nationale
  qc_10: prov_qc_hlthreg_capitale_nationale
  qc_11: prov_qc_hlthreg_capitale_nationale
  qc_12: prov_qc_hlthreg_capitale_nationale
  qc_13: prov_qc_hlthreg_capitale_nationale
  qc_14: prov_qc_hlthreg_capitale_nationale
  qc_15: prov_qc_hlthreg_capitale_nationale
  qc_16.1: prov_qc_hlthreg_capitale_nationale
  qc_16.2: prov_qc_hlthreg_capitale_nationale
  qc_16.3: prov_qc_hlthreg_capitale_nationale
  qc_16.4: prov_qc_hlthreg_capitale_nationale
  mtl_01: prov_qc_hlthreg_montreal
  mtl_02: prov_qc_hlthreg_montreal
  mtl_05: prov_qc_hlthreg_montreal
  mtl_08.1: prov_qc_hlthreg_montreal
  mtl_08.2: prov_qc_hlthreg_montreal
  mtl_11: prov_qc_hlthreg_montreal
  mtl_12: prov_qc_hlthreg_montreal
  mtl_16: prov_qc_hlthreg_montreal
  riki_01: prov_qc_hlthreg_bas_saint_laurent
  rdl_01: prov_qc_hlthreg_bas_saint_laurent
  stak_01: prov_qc_hlthreg_bas_saint_laurent
  stak_02: prov_qc_hlthreg_bas_saint_laurent
  trpis_01: prov_qc_hlthreg_bas_saint_laurent
  mtne_01: prov_qc_hlthreg_bas_saint_laurent
  lvl_01: prov_qc_hlthreg_laval
  lvl_02: prov_qc_hlthreg_laval
  lvl_03: prov_qc_hlthreg_laval
  lvl_04: prov_qc_hlthreg_laval
  lvl_05: prov_qc_hlthreg_laval
  gtn_01: prov_qc_hlthreg_outaouais
