# This is the configuration file for the data ingestion pipeline script for the province of Québec
# modelEAU lab

colors:
    "0":
      french: "Pas de données"
      english: "No Data"
      color: "#ececec"
    "1":
      french: "Très faible"
      english: "Very Low"
      color: "#6da06f"
    "2":
      french: "Faible"
      english: "Low"
      color: "#b6e9d1"
    "3":
      french: "Moyennement élevé"
      english: "Somewhat high"
      color: "#ffbb43"
    "4":
      french: "Élevé"
      english: "High"
      color: "#ff8652"
    "5":
      french: "Très élevé"
      english: "Very high"
      color: "#c13525"

lod: 0.5

default_start_date: "2022-03-01"

data_folder: "/Users/jeandavidt/Library/CloudStorage/OneDrive-UniversitéLaval/Université/Doctorat/COVID/Latest Data/Input"
csv_folder: "/Users/jeandavidt/Library/CloudStorage/OneDrive-UniversitéLaval/Université/Doctorat/COVID/Latest Data/odm_csv_2022"

polygon_output_dir: "/Users/jeandavidt/Library/CloudStorage/OneDrive-UniversitéLaval/Université/Doctorat/COVID/Website geo"
site_output_dir: "/Users/jeandavidt/Library/CloudStorage/OneDrive-UniversitéLaval/Université/Doctorat/COVID/Website geo"

plot_output_dir: "/Users/jeandavidt/Library/CloudStorage/OneDrive-UniversitéLaval/Université/Doctorat/COVID/Website figures 2022"
city_output_dir: "/Users/jeandavidt/Library/CloudStorage/OneDrive-UniversitéLaval/Université/Doctorat/COVID/Latest Data/wide tables 2022"

static_data: "Ongoing/CentrEAU-COVID_Static_Data.xlsx"

inspq_data: ""
inspq_vaccine_data: ""

bsl_cities:
  - "stak"
  - "trpis"
  - "mtne"
  - "riki"
  - "rdl"

qc_lab_data: "Ongoing/COVIDProject_Lab Measurements.xlsx"
qc_sheet_name: "Lab analyses"
qc_lab: "modeleau_lab"

qc_city_sensor_folder: "2022/Qc_sensors"
qc_city_plant_folder: "2022/Qc_plant"

qc_virus_data: "2022/CentrEau-COVID_Resultats_Quebec_2022.xlsx"
qc_virus_sheet_name: "QC Data Daily Samples (McGill)"
qc_quality_sheet_name: "QC_Compil_STEP (int)"
qc_virus_lab: "frigon_lab"

poly_name: "polygons_2022.geojson"
polys_to_extract:
  - "swrCat"

site_name: "sites2022.geojson"

plot_langs:
  - "french"

